### ISSUE TITLE
Wrong canvas scale

### ISSUE THREAD

**Issue by josemmc95** [scribble-rs/scribble.rs#96]
With the recent updates, the scale of the canvas is not the same on all devices.

For example, if you draw in a phone, in a fhd monitor you will only see a small portion of it.

And if you draw in the pc, the phone will only see the corner.

It was working before you made the refactor.

Example:

![](https://i.imgur.com/iyXjfAm.png)

![](https://i.imgur.com/ykCQlSM.png)

Thank you in advanced.

**Comment by kiwy42** [comment]
I'm not sure if related. 
I was playing today, and 2 of my friends where having troubles.
One of then had a resolution of 4K while we mostly have 1080p screen.
here's the result oin my 1080p screen: 
![image](https://user-images.githubusercontent.com/44195818/78460994-ee7c9b80-76c5-11ea-9f67-96f12ab0e072.png)
And here's waht my friend was having on his 4K screen: 
![image](https://user-images.githubusercontent.com/44195818/78461016-271c7500-76c6-11ea-9de0-6493e3514af6.png)
I think it's a similar issue.
Hope this could help identify the issue.

**Comment by josemmc95** [comment]
> I'm not sure if related.
> I was playing today, and 2 of my friends where having troubles.
> One of then had a resolution of 4K while we mostly have 1080p screen.
> here's the result oin my 1080p screen:
> ![image](https://user-images.githubusercontent.com/44195818/78460994-ee7c9b80-76c5-11ea-9f67-96f12ab0e072.png)
> And here's waht my friend was having on his 4K screen:
> ![image](https://user-images.githubusercontent.com/44195818/78461016-271c7500-76c6-11ea-9de0-6493e3514af6.png)
> I think it's a similar issue.
> Hope this could help identify the issue.
> [edit:] I can confirm after a test that setting its resoltuion to 1080p instead of 4K solve the issue.

Yes, I think it's the same problem.

**Comment by Bios-Marcel** [comment]
I just checked. This is due to the window scaling PR.

**Comment by Bios-Marcel** [comment]
Can you check the latest commit and see what changed? It seems to work with window zoom for now. Not sure about high DPI with system zoom. Also, mobile isn't really supported anyway, just saying. This must be unplayable on mobile. Please test using your own instance, as mine doesn't run the latest commits, since I don't deem them stable yet.

**Comment by josemmc95** [comment]
> Can you check the latest commit and see what changed? It seems to work with window zoom for now. Not sure about high DPI with system zoom. Also, mobile isn't really supported anyway, just saying. This must be unplayable on mobile. Please test using your own instance, as mine doesn't run the latest commits, since I don't deem them stable yet.

Nope, same problem but it get worse, because now the canvas is even bigger and doesn't adapt to the screen.

**Comment by Bios-Marcel** [comment]
Can you give me info about your screen, your system settings, your browser and your page zoom factor? Additionally please try drawing a line ftom top left to bottom right and send a screenshot.

**Comment by josemmc95** [comment]
It's a FHD monitor and I have a 1920 x 1080 screen resolution, using safari and page zoom is default (100% I think). 

![](https://i.imgur.com/KUe8yRF.png)

**Comment by Bios-Marcel** [comment]
Can't reproduce this with my android device :thinking:

**Comment by josemmc95** [comment]
> Can't reproduce this with my android device 🤔

It's fixed with the latest commit, but there is the problem that the canvas is bigger than before and we can see the tools, like this pic:

![image](https://user-images.githubusercontent.com/62221854/78472635-ddba3d00-773a-11ea-88e0-f92d29bfe007.png)

And another problem related with safari is that safari doesn't call OnCloseHandler, I replaced the call in wsListen with game.OnDisconnect(....) and commented the OnCloseHandler.

It's not related with this bug but It's a bug hahaha

**Comment by Bios-Marcel** [comment]
Yo, do the problems persist with the latest version? Just test with the official instance please.

**Comment by josemmc95** [comment]
> Yo, do the problems persist with the latest version? Just test with the official instance please.

It's fixed! And now it resizes!!!

Thank you a lot!!

**Comment by Bios-Marcel** [comment]
Cool, now there's just the problem that it clears the canvas when resizing ^^

**Comment by josemmc95** [comment]
> Cool, now there's just the problem that it clears the canvas when resizing ^^

Mmm interesting...

Maybe there is something to transform the current draw in relation with the new size.

I don't know if is better to disable resize or clear canvas for every user if you can't fix it...

**Comment by josemmc95** [comment]
With this code it works but the canvas get blury...

I'll keep investigating tomorrow.

```
function handleCanvasResize() {
        let tempCanvas = document.createElement('canvas');
        tempCanvas.width = drawingBoard.width;
        tempCanvas.height = drawingBoard.height;
        tempCanvas.getContext('2d').drawImage(drawingBoard, 0, 0);
        drawingBoard.width = drawingBoard.clientWidth;
        drawingBoard.height = drawingBoard.clientHeight;
        drawingBoard.getContext('2d').drawImage(tempCanvas, 0, 0, tempCanvas.width, tempCanvas.height, 0, 0, drawingBoard.width, drawingBoard.height);
        setLineWidth(localLineWidthUnscaled);
        chat.style.maxHeight = drawingBoard.height + "px";
    }
```

**Comment by Bios-Marcel** [comment]
Open in the form of #106
